name: Dev to Main

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies then run tests
        working-directory: ./frontend
        run: npm install | npm test

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Backend Dependencies then run tests
        working-directory: ./backend
        run: npm install | npm test

  build:
    needs: build_test
    runs-on: ubuntu-latest
    if: success()

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push the backend Docker image
      run: docker build ./backend -t alange20/e2e_backend:latest | docker push alange20/e2e_backend:latest

    - name: Build and Push the frontend the Docker image
      run: docker build ./frontend -t alange20/e2e_frontend:latest | docker push alange20/e2e_frontend:latest
